### ISSUE TITLE
Mail doesn't open on Flutter Web when body content is too long

### ISSUE THREAD

**Issue by melwinlobo18** [smaho-engineering/mailto#6]
When the **body** of the mail is too long the Mail app doesn't open on Flutter web. Not sure about the behavior on mobile (haven't tested).

Link to the [gist](https://gist.github.com/a43fb164edc3a6b6a954533ec340b272).

**Comment by melwinlobo18** [comment]
Any updates on this?👀

**Comment by vincevargadev** [comment]
Hi @melwinlobo18. Thank you for opening an issue. It's a very interesting edge case!

The email body in your example is 5250+ characters long. I would not be surprised if the mailto links in the browser or email client would have [similar limitations](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) as the URLs. The issue is very likely to be present outside of Flutter web, too (for example, create something similar in plain HTML).

I wouldn't hold my breath for a fix, I'd expect that this issue is outside of our control.

If you need to send that much information from your users, I'd suggest using a form with some backend (tech stack is up to you) to handle that for you.
